---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: debian-7
  - name: debian-8
    run_list:
      - recipe[build-essential]

suites:
  - name: default
    run_list:
      - recipe[glances]
