# <% load "#{File.dirname(__FILE__)}/test/kitchen-docker.rb" %>
---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: debian-6
    attributes:
      glances:
        extra_pip_packages: # For python 2.6
          - logutils
          - argparse
  - name: debian-7
  - name: debian-8
  - name: centos-5
    attributes:
      glances:
        extra_pip_packages:
          - logutils
          - argparse
  - name: centos-6
    attributes:
      glances:
        extra_pip_packages:
          - logutils
          - argparse
  - name: centos-7
    driver_config:
      dockerfile: test/dockerfiles/centos7
      privileged: true
      run_command: /usr/sbin/init
      private_key:
      public_key:
  - name: fedora-20
  - name: fedora-21

suites:
  - name: glances
    run_list:
      - recipe[build-essential]
      - recipe[glances]
  - name: glances-service
    excludes:
      # FIXME: systemd support for these platforms:
      - fedora-20
      - fedora-21
    run_list:
      - recipe[build-essential]
      - recipe[glances::service]
    attributes:
      glances:
        service:
          RUN: true
