---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  chef_license: accept

verifier:
  name: inspec
  sudo: false

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
      - recipe[locales]
  - name: ubuntu-18.04
    run_list:
      - recipe[apt]
  - name: debian-9
    run_list:
      - recipe[apt]
  - name: debian-10
    run_list:
      - recipe[apt]
  - name: centos-7
    run_list:
      - recipe[yum-epel]
    attributes:
      glances:
        service:
          DAEMON: /usr/bin/glances

suites:
  - name: glances
    run_list:
      - recipe[build-essential]
      - recipe[glances]
  - name: glances-service
    run_list:
      - recipe[build-essential]
      - recipe[glances::service]
    attributes:
      glances:
        service:
          RUN: true
    excludes:
      - debian-9
      - debian-10
      - ubuntu-16.04
      - ubuntu-18.04
      - centos-7
