---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.6
  - name: debian-8.1

suites:
  - name: default
    run_list:
      - recipe[glances]
    attributes:
      glances:
        config:
          cpu:
            user_careful: 50
